(function(){
  const original=renderProductTab;
  renderProductTab=async function(tab){
    if(tab!=='memorial')return original(tab);
    PRODUCT.tab=tab;
    $$('[data-producttab]').forEach(b=>b.classList.toggle('active',b.dataset.producttab===tab));
    await renderMemorial();
  };

  async function renderMemorial(){
    const panel=$('#productPanel');
    panel.innerHTML='<div class="loading">正在整理可选的日记…</div>';
    let items=[],status={published:false},cloudError='',config={url:'',configured:false,has_token:false};
    try{items=(await api('/api/memorial/available',{noCache:true})).items||[]}catch(e){panel.textContent=e.message;return}
    try{config=await api('/api/memorial/config',{noCache:true})}catch(e){cloudError=e.message}
    if(config.configured)try{status=await api('/api/memorial/status',{noCache:true})}catch(e){cloudError=e.message}
    let draft={};
    try{const stored=JSON.parse(localStorage.getItem('lifeosMemorialDraft')||'{}');if(stored&&typeof stored==='object'&&!Array.isArray(stored))draft=stored}catch{}
    const selected=new Set((Array.isArray(draft.entry_ids)?draft.entry_ids:status.entry_ids||[]).filter(x=>items.some(e=>e.entry_id===x)));
    const highlights=new Set((Array.isArray(draft.story_ids)?draft.story_ids:status.story_ids||[]).filter(x=>selected.has(x)).slice(0,12));
    panel.innerHTML=`<div class="productPanelInner memorialEditor">${productIntro('','纪念页','')}
      <div class="memorialSteps"><span>01 · 编辑</span><span>02 · 预览</span><span>03 · 发布与制码</span></div>
      <div class="settingCard"><h4>Netlify 免费发布</h4><p>先把纪念页项目部署到 Netlify，在站点的环境变量中设置 <code>MEMORIAL_PUBLISH_TOKEN</code>。</p><div class="actions"><button class="productAction" id="memGenerateToken" type="button">${config.has_token?'重新生成发布密钥':'生成发布密钥'}</button><a class="productAction" href="https://app.netlify.com/" target="_blank" rel="noopener">打开 Netlify ↗</a></div><div id="memTokenResult" class="memorialTokenResult" hidden></div><label class="fieldLabel">Netlify 站点地址<input class="input" id="memSiteUrl" type="url" placeholder="https://your-site.netlify.app" value="${esc(config.url||'')}"></label><div class="actions"><button class="productAction" id="memSaveSite" type="button">保存网址并检查连接</button></div><p class="small">首次部署后才会有站点网址。免费站点有每月额度，额度耗尽时页面会暂停；刻印前请确认网址能长期由你管理。</p></div>
      ${cloudError?`<div class="privacyNotice">Netlify 连接状态：${esc(cloudError)}</div>`:''}
      ${status.published?`<div class="memorialLive"><b>公开页已发布</b><a href="${esc(status.url)}" target="_blank" rel="noopener">打开当前页面 ↗</a><span>${status.entry_count} 页 · 固定网址</span></div>`:''}
      <div class="settingsGrid"><div class="settingCard"><label class="fieldLabel">页面标题<input class="input" id="memTitle" maxlength="180" value="${esc(draft.title??status.title??'我留下的故事')}" placeholder="例如：一个普通人的一生"></label><label class="fieldLabel">写给来访者的话<textarea class="input" id="memIntro" maxlength="4000" rows="7" placeholder="用自己的话，告诉他们你想留下什么。">${esc(draft.introduction??status.introduction??'')}</textarea></label></div><div class="settingCard"><h4>阅读顺序</h4><p>“精选故事”从下面标记的日记中挑出；“完整档案”是所有勾选的日记。</p><div class="memorialCount" id="memCount"></div><label class="memorialToggle"><input id="memAI" type="checkbox" ${draft.ai_enabled??status.ai_enabled?'checked':''}> 允许访客根据公开日记向 AI 提问</label><p class="small">AI 不能代表你本人。需要线上服务器另行配置模型及费用上限；未配置时会显示暂不可用。</p></div></div>
      <div class="settingCard"><div class="memorialSelectHead"><div><h4>选择公开日记</h4><p>发布前请逐页检查隐私信息。</p></div><div class="actions"><button class="productAction" id="memAll">全选</button><button class="productAction" id="memNone">全不选</button></div></div><input class="input" id="memSearch" type="search" placeholder="按日期或标题查找" aria-label="查找日记"><div class="memorialEntryList" id="memEntries"></div></div>
      <div class="settingCard memorialPreview" id="memPreview" hidden></div>
      <div class="writerFoot"><span class="writerDraft">发布后，所有持有网址的人都能阅读所选文字。</span><div class="actions"><button class="productAction" id="memPreviewButton">预览将公开的内容</button><button class="productAction primary" id="memPublish" ${cloudError||!config.configured?'disabled':''}>${status.published?'更新公开页':'发布公开页'}</button></div></div>
      ${status.published?`<div class="memorialPublishTools"><div><b>用于刻印的二维码</b><p>请在实际刻印前用两部手机扫码测试，并妥善保管域名和服务器。</p><img src="/api/memorial/qr?view=1&url=${encodeURIComponent(status.url)}" alt="公开纪念页二维码"><div class="actions"><a class="productAction" href="/api/memorial/qr?url=${encodeURIComponent(status.url)}">下载高清 SVG</a><button class="productAction" id="memCopy">复制网址</button><button class="productAction" id="memUnpublish">撤下公开页</button></div></div></div>`:''}
    </div>`;
    let shown=200;
    const renderList=()=>{const q=$('#memSearch').value.trim().toLowerCase(),list=$('#memEntries');list.replaceChildren();const matches=items.filter(x=>(x.date+' '+x.title).toLowerCase().includes(q));for(const e of matches.slice(0,shown)){const row=document.createElement('div');row.className='memorialEntry';const choice=document.createElement('input');choice.type='checkbox';choice.checked=selected.has(e.entry_id);choice.setAttribute('aria-label','公开 '+e.date+' '+e.title);choice.onchange=()=>{choice.checked?selected.add(e.entry_id):selected.delete(e.entry_id);if(!choice.checked)highlights.delete(e.entry_id);updateCount()};const star=document.createElement('input');star.type='checkbox';star.checked=highlights.has(e.entry_id);star.disabled=!choice.checked;star.setAttribute('aria-label','精选 '+e.date+' '+e.title);star.onchange=()=>{if(star.checked&&highlights.size>=12){star.checked=false;toast('精选故事最多 12 篇');return}star.checked?highlights.add(e.entry_id):highlights.delete(e.entry_id);updateCount()};choice.addEventListener('change',()=>{star.disabled=!choice.checked;star.checked=highlights.has(e.entry_id)});const name=document.createElement('button');name.type='button';name.textContent=e.date+' · '+e.title;name.onclick=()=>showEntry(e.entry_id);row.append(choice,name,star);list.append(row)}if(!list.children.length)list.textContent='没有匹配的日记。';if(matches.length>shown){const more=document.createElement('button');more.type='button';more.className='productAction';more.textContent=`继续查看（还有 ${matches.length-shown} 篇）`;more.onclick=()=>{shown+=200;renderList()};list.append(more)}updateCount()};
    const updateCount=()=>{$('#memCount').textContent=`${selected.size} 页公开日记 · ${highlights.size} 篇精选故事`;saveDraft()};
    const saveDraft=()=>{try{localStorage.setItem('lifeosMemorialDraft',JSON.stringify({title:$('#memTitle').value,introduction:$('#memIntro').value,ai_enabled:$('#memAI').checked,entry_ids:[...selected],story_ids:[...highlights]}))}catch{}};
    $('#memGenerateToken').onclick=async()=>{if(config.has_token&&!confirm('重新生成后，必须把新的密钥更新到 Netlify 环境变量；旧密钥会失效。继续吗？'))return;try{const result=await post('/api/memorial/config',{generate:true});const box=$('#memTokenResult');box.hidden=false;box.replaceChildren();const note=document.createElement('p');note.textContent='只显示这一次：复制下面的密钥，在 Netlify 站点环境变量 MEMORIAL_PUBLISH_TOKEN 中粘贴相同内容。';const code=document.createElement('code');code.textContent=result.generated_token;const copy=document.createElement('button');copy.className='productAction';copy.textContent='复制密钥';copy.onclick=async()=>{await navigator.clipboard.writeText(result.generated_token);toast('密钥已复制')};box.append(note,code,copy);config=result;$('#memGenerateToken').textContent='重新生成发布密钥'}catch(e){toast(e.message)}};
    $('#memSaveSite').onclick=async()=>{try{await post('/api/memorial/config',{url:$('#memSiteUrl').value.trim()});toast('已保存，正在检查连接');await renderMemorial()}catch(e){toast(e.message)}};
    async function showEntry(id){const box=$('#memPreview');box.hidden=false;box.textContent='正在读取原文…';try{const e=await api('/api/entry?entry_id='+encodeURIComponent(id),{noCache:true});box.replaceChildren();const h=document.createElement('h4');h.textContent=e.entry?.title||e.entry?.journal_date||'一页日记';const pre=document.createElement('pre');pre.textContent=e.current?.content||'';box.append(h,pre);box.scrollIntoView({behavior:'smooth',block:'nearest'})}catch(e){box.textContent=e.message}}
    $('#memSearch').oninput=()=>{shown=200;renderList()};$('#memAll').onclick=()=>{items.forEach(x=>selected.add(x.entry_id));renderList()};$('#memNone').onclick=()=>{selected.clear();highlights.clear();renderList()};
    $('#memTitle').oninput=saveDraft;$('#memIntro').oninput=saveDraft;$('#memAI').onchange=saveDraft;
    $('#memPreviewButton').onclick=()=>{const box=$('#memPreview');box.hidden=false;box.replaceChildren();const h=document.createElement('h4');h.textContent='发布预览';const p=document.createElement('p');p.textContent=`标题：${$('#memTitle').value}。将公开 ${selected.size} 篇日记，其中 ${highlights.size} 篇作为精选故事。AI 提问：${$('#memAI').checked?'开启':'关闭'}。`;const intro=document.createElement('pre');intro.textContent=$('#memIntro').value;box.append(h,p,intro);box.scrollIntoView({behavior:'smooth',block:'nearest'})};
    $('#memPublish').onclick=async()=>{if(!$('#memTitle').value.trim()||!$('#memIntro').value.trim()||!selected.size)return toast('请填写标题、前言并选择日记');if(!highlights.size)return toast('请至少标记一篇精选故事');if(!confirm(`确认公开 ${selected.size} 篇日记全文？访客可以从任何地方阅读、复制和保存这些文字。`))return;const b=$('#memPublish');b.disabled=true;b.textContent='正在发布…';try{await post('/api/memorial/publish',{title:$('#memTitle').value,introduction:$('#memIntro').value,entry_ids:[...selected],story_ids:[...highlights],ai_enabled:$('#memAI').checked});toast('公开页已发布');await renderMemorial()}catch(e){toast(e.message);b.disabled=false;b.textContent='发布公开页'}};
    if($('#memCopy'))$('#memCopy').onclick=async()=>{await navigator.clipboard.writeText(status.url);toast('网址已复制')};
    if($('#memUnpublish'))$('#memUnpublish').onclick=async()=>{if(!confirm('确认撤下公开页？二维码将暂时无法打开。以后重新发布仍使用原网址。'))return;const b=$('#memUnpublish');b.disabled=true;try{await post('/api/memorial/unpublish',{});toast('公开页已撤下');await renderMemorial()}catch(e){toast(e.message);b.disabled=false}};
    renderList();
  }
})();
