'use strict';
// Pure renderer QA: public GIFs only, no diary backend or user profile is opened.
const {app,BrowserWindow}=require('electron');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),out=path.join(ROOT,'docs','qa_vivi','run-'+Date.now());fs.mkdirSync(out,{recursive:true});
app.setPath('userData',path.join(out,'profile'));let win,server;const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),checks=[],errors=[];
const html=`<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/vivi-pet.css"><style>body{margin:0;background:#f8f4ec;color:#38333b;font:16px Georgia,serif}main{padding:32px}h1{font-weight:400}.stage{width:800px;height:560px;position:relative;border-bottom:1px solid #c7bdb0;overflow:hidden}.pet{position:absolute}.preview{display:grid;grid-template-columns:repeat(7,110px);gap:12px}.sample{width:100px;height:130px;border-bottom:1px solid #ded5c9}.sample label{font-size:12px;display:block;margin-top:5px}</style><main><h1>ViVi · original animation renderer</h1><div class="preview"></div><div class="stage"><div class="pet" tabindex="0"></div></div></main><script src="/pet-actions.js"></script><script src="/vivi-pet.js"></script><script src="/pet-renderers.js"></script>`;
async function verifyAutomaticEdge(js,until){
  await js(`window.edgeHost=document.createElement('div');edgeHost.className='pet';document.querySelector('.stage').append(edgeHost);window.edgeLog=[];window.edgeFrames=[];window.edgeRolls=[0,.4,0,0,0,0];window.edgePet=lifeosViVi.mount(edgeHost,manifest,{mode:'companion',width:96,height:104,positionElement:edgeHost,position:{x:36,y:280},bounds:()=>({width:800,height:560}),settings:{autoBehavior:true,edgeHide:true},random:()=>edgeRolls.length?edgeRolls.shift():.1,onBehavior:value=>edgeLog.push(value),onFrame:value=>edgeFrames.push(value)});await edgePet.ready`);
  await until(`edgePet.getState().hiddenEdge==='left'&&edgePet.element.dataset.action==='hide'`);
  const hidden=await js(`return edgePet.getState()`);assert.equal(hidden.behavior.cycles_remaining,2);assert.equal(hidden.manualLoop,null);assert.equal(hidden.onceAction,null);fs.writeFileSync(path.join(out,'ViVi-自动藏边.png'),(await win.webContents.capturePage()).toPNG());
  await until(`edgeLog.some(value=>value.action==='walk_right')&&edgePet.getState().hiddenEdge===null`);
  const result={hidden,...await js(`return{visible:edgePet.getState(),log:edgeLog,frames:edgeFrames}`)};assert.deepEqual(result.log.slice(0,4).map(value=>value.action),['sit','walk_left','hide','walk_right']);assert.ok(result.log[3].time-result.log[2].time>=2300-35&&result.log[3].time-result.log[2].time<2500);
  for(const id of ['sit','walk_left','hide']){const group=result.frames.filter(value=>value.action===id);assert.equal(group.length,id==='walk_left'?38:46);const count=id==='walk_left'?19:23;assert.deepEqual(group.map(value=>value.frame),Array.from({length:count*2},(_,i)=>i%count));}
  fs.writeFileSync(path.join(out,'automatic-edge.json'),JSON.stringify(result,null,2));await js(`edgePet.destroy();edgeHost.remove()`);checks.push('edge arrival finishes its walking cycle, hides for finite source cycles, and comes back automatically');return result;
}
async function run(){
  server=http.createServer((request,response)=>{
    const uri=new URL(request.url,'http://localhost').pathname;
    if(uri==='/'){response.setHeader('Content-Type','text/html; charset=utf-8');response.end(html);return;}
    const allowed=['/vivi-pet.js','/vivi-pet.css','/pet-actions.js','/pet-renderers.js'].includes(uri)||/^\/assets\/pets\/vivi\/[a-z0-9_.-]+$/.test(uri);
    if(!allowed){response.writeHead(404);response.end();return;}
    const file=path.join(ROOT,'app',uri);if(!fs.existsSync(file)){response.writeHead(404);response.end();return;}
    response.setHeader('Content-Type',uri.endsWith('.js')?'text/javascript':uri.endsWith('.css')?'text/css':uri.endsWith('.json')?'application/json':'image/gif');fs.createReadStream(file).pipe(response);
  });await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  win=new BrowserWindow({width:1000,height:900,show:false,webPreferences:{contextIsolation:true,sandbox:true,nodeIntegration:false,offscreen:true,backgroundThrottling:false}});await win.loadURL(`http://127.0.0.1:${server.address().port}`);
  win.webContents.on('console-message',event=>{if(event.level==='error')errors.push(event.message)});
  const js=code=>win.webContents.executeJavaScript(`(async()=>{${code}})()`),until=async condition=>{for(let i=0;i<100;i++){if(await js('return '+condition))return;await wait(80)}throw Error('Wait failed: '+condition)};
  await js(`window.renderMetrics={decoderCreates:0,decoderCloses:0,decodeCalls:0,gifRequests:0,decodeTimes:[]};window.realDecoder=ImageDecoder;ImageDecoder=new Proxy(realDecoder,{construct(Type,args){renderMetrics.decoderCreates++;const value=new Type(...args),decode=value.decode.bind(value),close=value.close.bind(value);value.decode=async options=>{renderMetrics.decodeCalls++;const start=performance.now();try{return await decode(options)}finally{renderMetrics.decodeTimes.push(performance.now()-start)}};value.close=()=>{renderMetrics.decoderCloses++;return close()};return value}});window.realFetch=fetch;window.fetch=(url,...args)=>{if(String(url).endsWith('.gif'))renderMetrics.gifRequests++;return realFetch(url,...args)}`);
  await js(`window.manifest=await (await fetch('/assets/pets/vivi/pet.json')).json();window.positions=[];window.pet=lifeosViVi.mount(document.querySelector('.pet'),manifest,{mode:'companion',width:144,height:156,interactive:true,positionElement:document.querySelector('.pet'),world:document.querySelector('.stage'),bounds:()=>({width:800,height:560}),position:{x:450,y:380},onPosition:p=>positions.push(p)});await pet.ready`);
  if(process.env.VIVI_EDGE_ONLY==='1'){await js(`await pet.select('sit')`);const result=await verifyAutomaticEdge(js,until);await js(`pet.destroy()`);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({ok:true,checks,edge:result,consoleErrors:errors},null,2));console.log(JSON.stringify({ok:true,checks:checks.length,out}));return;}
  const performanceReport=await js(`window.benchmarkPets=[];await pet.select('sit');for(let i=0;i<2;i++){const host=document.createElement('div');document.querySelector('.preview').append(host);const sample=lifeosViVi.mount(host,manifest,{mode:'preview',width:144,height:156});await sample.ready;await sample.select('sit');benchmarkPets.push(sample)}const before={...renderMetrics};await new Promise(resolve=>setTimeout(resolve,2500));const loopDecodes=renderMetrics.decodeCalls-before.decodeCalls,warmStart=renderMetrics.decodeCalls;await new Promise(resolve=>setTimeout(resolve,2300));const warmLoopDecodes=renderMetrics.decodeCalls-warmStart;const selections=[];for(const id of ['sit','fly','interact','sit','fly','interact']){const start=performance.now();await pet.select(id);selections.push({id,ms:performance.now()-start})}const metrics=JSON.parse(JSON.stringify(renderMetrics));benchmarkPets.forEach(p=>p.destroy());benchmarkPets=[];document.querySelector('.preview').replaceChildren();return{same_action_mounts:3,loop_duration_ms:2500,loop_decode_calls:loopDecodes,warm_loop_duration_ms:2300,warm_loop_decode_calls:warmLoopDecodes,selections,metrics,cache:lifeosViVi.cacheStats?.()||null}`);
  fs.writeFileSync(path.join(out,'performance.json'),JSON.stringify(performanceReport,null,2));
  if(process.env.VIVI_PERF_ONLY==='1'){await js('pet.destroy()');console.log(JSON.stringify({ok:true,performance:performanceReport,out}));return;}
  assert.ok(performanceReport.loop_decode_calls<=30);assert.equal(performanceReport.warm_loop_decode_calls,0);assert.equal(performanceReport.metrics.gifRequests,4);checks.push('three instances share four GIF downloads and cached loops need no new decodes');
  assert.equal(await js(`return typeof ImageDecoder`),'function');await until(`pet.getState().frame>0`);
  const alpha=()=>js(`const canvas=pet.element.querySelector('canvas'),data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let count=0;for(let i=3;i<data.length;i+=4)if(data[i])count++;return count`);
  assert.ok(await alpha()>500);checks.push('GIF ImageDecoder draws a visible transparent character and advances original frames');
  const ids=await js(`return [...new Set(manifest.actions.map(a=>a.asset))].map(asset=>manifest.actions.find(a=>a.asset===asset).id)`);
  const visible={};
  for(const id of ids){await js(`await pet.select('${id}');pet.setMotion(false)`);visible[id]=await alpha();if(!visible[id]){await js(`pet.setMotion(true)`);await until(`pet.getState().frame>=2`);await js(`pet.setMotion(false)`);visible[id]=await alpha();}assert.ok(visible[id]>20,id+' has visible animation content');await js(`pet.setMotion(true)`);}
  assert.equal(ids.length,14);checks.push('all fourteen distinct source GIFs render without converting to the nine-row sprite contract');
  await js(`window.frameHost=document.createElement('div');document.querySelector('.preview').append(frameHost);window.activeFrameLog=null;window.sequencePet=lifeosViVi.mount(frameHost,manifest,{mode:'preview',width:144,height:156,onFrame:value=>{if(activeFrameLog)activeFrameLog.push(value)}});await sequencePet.ready`);
  const frameReports=[];
  for(const id of ids){
    const result=await js(`window.activeFrameLog=[];return await new Promise((resolve,reject)=>sequencePet.select('${id}',{loop:false,onComplete:value=>{const log=activeFrameLog;activeFrameLog=null;resolve({...value,log,after:sequencePet.getState()})}}).catch(reject))`);
    const descriptor=await js(`return manifest.actions.find(value=>value.id==='${id}')`);assert.deepEqual(result.log.map(value=>value.frame),Array.from({length:descriptor.frames},(_,i)=>i));assert.deepEqual(result.log.map(value=>value.duration_ms),descriptor.frame_durations_ms);assert.equal(result.frames,descriptor.frames);assert.equal(result.after.onceAction,null);assert.equal(result.after.action,'sit');
    const intervals=result.log.slice(1).map((value,i)=>value.time-result.log[i].time),expected=descriptor.frame_durations_ms.slice(0,-1),average=intervals.reduce((a,b)=>a+b,0)/intervals.length,expectedAverage=expected.reduce((a,b)=>a+b,0)/expected.length;
    assert.ok(Math.abs(average-expectedAverage)<4,id+' keeps original average frame interval');assert.ok(result.elapsed_ms>=descriptor.duration_ms-35&&result.elapsed_ms<descriptor.duration_ms+450,id+' completes at original total duration');
    frameReports.push({action:id,frames:descriptor.frames,source_duration_ms:descriptor.duration_ms,actual_duration_ms:result.elapsed_ms,source_fps:descriptor.frames/(descriptor.duration_ms/1000),actual_fps:descriptor.frames/(result.elapsed_ms/1000),mean_frame_interval_ms:average,source_mean_frame_interval_ms:expectedAverage,intervals_ms:intervals,sequence:result.log});
  }
  assert.equal(frameReports.reduce((sum,value)=>sum+value.frames,0),615);fs.writeFileSync(path.join(out,'frame-sequences.json'),JSON.stringify(frameReports,null,2));checks.push('all fourteen actions present all 615 original frames in order, at original GIF timing, once before returning to automatic behavior');
  await js(`window.pausedLog=[];window.activeFrameLog=pausedLog;window.pausedComplete=null;await sequencePet.select('fly',{loop:false,onComplete:value=>{pausedComplete=value;activeFrameLog=null}})`);await wait(260);
  assert.equal(await js(`return await sequencePet.playOnce('interact',{force:false})`),false);assert.equal(await js(`return await sequencePet.interact()`),false);await js(`sequencePet.setMotion(false);window.pausedCount=pausedLog.length;sequencePet.resize(120,130)`);await wait(260);assert.equal(await js(`return pausedLog.length`),await js(`return pausedCount`));await js(`sequencePet.setMotion(true)`);await until(`Boolean(pausedComplete)`);assert.deepEqual(await js(`return pausedLog.map(value=>value.frame)`),Array.from({length:35},(_,i)=>i));checks.push('pause/resize preserve the current one-shot frame and normal app events cannot interrupt it');
  await js(`window.dragFrameLog=[];window.dragCompleted=null;window.dragHost=document.createElement('div');dragHost.className='pet';document.querySelector('.stage').append(dragHost);window.dragPet=lifeosViVi.mount(dragHost,manifest,{mode:'companion',width:144,height:156,positionElement:dragHost,position:{x:400,y:250},bounds:()=>({width:800,height:560}),onFrame:value=>{if(dragFrameLog)dragFrameLog.push(value)}});await dragPet.ready;dragFrameLog=[];const selecting=dragPet.select('fly',{loop:false,onComplete:value=>dragCompleted=value});dragPet.resize(180,195);await selecting;window.dragGeneration=dragPet.getState().animation.sequence`);await wait(230);
  await js(`dragPet.beginDrag({x:dragPet.getState().x+20,y:dragPet.getState().y+20});dragPet.moveDrag({x:350,y:300});dragPet.endDrag();dragPet.setSettings({autoBehavior:false});window.dragGenerationAfter=dragPet.getState().animation.sequence`);assert.equal(await js('return dragGeneration'),await js('return dragGenerationAfter'));await until(`Boolean(dragCompleted)`);assert.deepEqual(await js(`return dragFrameLog.filter(value=>value.sequence===dragGeneration).map(value=>value.frame)`),Array.from({length:35},(_,i)=>i));await js(`dragPet.destroy();dragHost.remove()`);checks.push('resize during action loading and dragging preserve the selected animation generation and complete frame sequence');
  await js(`window.cancelledCallbacks=[];await sequencePet.select('sleep',{loop:false,onComplete:()=>cancelledCallbacks.push('sleep')})`);await wait(100);await js(`await sequencePet.select('jump',{loop:false,onComplete:()=>cancelledCallbacks.push('jump')});await sequencePet.select(null)`);await wait(2200);assert.deepEqual(await js(`return cancelledCallbacks`),[]);await js(`sequencePet.destroy();frameHost.remove()`);checks.push('new commands and explicit cancellation discard obsolete completion callbacks');
  await js(`window.commandItem={...manifest,slug:manifest.id};lifeosPetActions.register(commandItem.slug,manifest.actions.map(value=>[value.id,value.label]));window.commandA=document.createElement('div');window.commandB=document.createElement('div');document.querySelector('.preview').append(commandA,commandB);window.commandOptionsA={mode:'preview',width:96,height:104};window.commandOptionsB={mode:'preview',width:96,height:104,motion:false};window.runtimeA=lifeosPetRenderers.paint(commandA,commandItem,commandOptionsA);window.runtimeB=lifeosPetRenderers.paint(commandB,commandItem,commandOptionsB);await Promise.all([runtimeA.ready,runtimeB.ready]);window.repaintCommands=()=>{lifeosPetRenderers.paint(commandA,commandItem,commandOptionsA);lifeosPetRenderers.paint(commandB,commandItem,commandOptionsB)};window.unsubscribeCommands=lifeosPetActions.subscribe(repaintCommands);window.firstCommand=lifeosPetActions.select(commandItem.slug,'fly');repaintCommands()`);
  await until(`lifeosPetActions.command(commandItem.slug)?.active===false`);assert.equal(await js(`return runtimeB.getState().onceAction`),'fly');assert.equal(await js(`return runtimeB.getState().frame`),0);await js(`repaintCommands();commandOptionsB.motion=true;repaintCommands()`);await until(`runtimeB.getState().onceAction===null`);
  const second=await js(`window.secondCommand=lifeosPetActions.select(commandItem.slug,'fly');repaintCommands();return{first:firstCommand,second:secondCommand}`);assert.notEqual(second.first,second.second);await until(`runtimeA.getState().onceAction==='fly'&&runtimeA.getState().frame>0`);await js(`lifeosPetActions.select(commandItem.slug,null);repaintCommands();unsubscribeCommands();lifeosPetRenderers.release(commandA);lifeosPetRenderers.release(commandB);commandA.remove();commandB.remove()`);checks.push('request commands retrigger identical actions and one preview completion never stops another instance mid-cycle');
  await js(`window.autoHosts=[],window.autoPets=[],window.autoLogs=[[],[],[]],window.autoFrames=[[],[],[]];function behaviorRandom(seed){let value=seed;return()=>{value=(Math.imul(value,1664525)+1013904223)>>>0;return value/4294967296}}for(let i=0;i<3;i++){const host=document.createElement('div');host.className='pet';document.querySelector('.stage').append(host);autoHosts.push(host);const runtime=lifeosViVi.mount(host,manifest,{mode:'companion',width:96,height:104,positionElement:host,position:{x:280+i*100,y:260},bounds:()=>({width:1600,height:560}),settings:{autoBehavior:true,edgeHide:false},...(i<2?{random:behaviorRandom(i===0?12345678:98123765)}:{}),onBehavior:value=>autoLogs[i].push(value),onFrame:value=>autoFrames[i].push(value)});autoPets.push(runtime);await runtime.ready}window.quietHost=document.createElement('div');document.querySelector('.stage').append(quietHost);window.quietLog=[];window.quietPet=lifeosViVi.mount(quietHost,manifest,{mode:'companion',width:96,height:104,position:{x:300,y:250},bounds:()=>({width:800,height:560}),settings:{autoBehavior:false},onBehavior:value=>quietLog.push(value)});await quietPet.ready;window.previewHost=document.createElement('div');document.querySelector('.preview').append(previewHost);window.previewBehaviorLog=[];window.stillPreview=lifeosViVi.mount(previewHost,manifest,{mode:'preview',width:96,height:104,onBehavior:value=>previewBehaviorLog.push(value)});await stillPreview.ready`);
  await until(`autoLogs[2].some(value=>value.reason==='choice')&&quietLog.length>=2`);checks.push('production Math.random triggers real autonomous action changes while disabled wandering uses only quiet poses');
  for(let i=0;i<130;i++){if(await js(`return autoLogs[0].length>=8&&autoLogs[1].length>=8`))break;await wait(300);}assert.ok(await js(`return autoLogs[0].length>=8&&autoLogs[1].length>=8`));
  const automaticReport=await js(`return{logs:autoLogs,frames:autoFrames,snapshots:autoPets.map(value=>value.getState()),quiet:quietLog,preview:stillPreview.getState(),preview_behavior:previewBehaviorLog}`);
  const safe=new Set(['sit','relax','sleep','special1','walk_left','walk_right','interact','jump','fly','sweat','special']);
  for(const [index,log] of automaticReport.logs.entries()){assert.ok(new Set(log.map(value=>value.action)).size>=(index<2?3:2));assert.ok(log.every(value=>safe.has(value.action)&&value.cycles>=1&&value.cycles<=5));for(let i=1;i<log.length;i++)assert.notEqual(log[i].action,log[i-1].action);}
  assert.notDeepEqual(automaticReport.logs[0].map(value=>value.action),automaticReport.logs[1].map(value=>value.action));assert.ok(automaticReport.logs.flat().some(value=>value.action.startsWith('walk_')));assert.ok(automaticReport.logs.flat().some(value=>['interact','jump','fly','sweat','special'].includes(value.action)));assert.ok(automaticReport.quiet.every(value=>['sit','relax','sleep','special1'].includes(value.action)));assert.deepEqual(automaticReport.preview_behavior,[]);assert.equal(automaticReport.preview.action,'sit');
  const descriptors=await js(`return manifest.actions`);for(const frames of automaticReport.frames){const groups=new Map();for(const value of frames){if(!groups.has(value.sequence))groups.set(value.sequence,[]);groups.get(value.sequence).push(value)}const completed=[...groups.values()].slice(0,-1);for(const group of completed){const descriptor=descriptors.find(value=>value.id===group[0].action);assert.equal(group.length%descriptor.frames,0);for(let i=0;i<group.length;i++)assert.equal(group[i].frame,i%descriptor.frames);}}
  fs.writeFileSync(path.join(out,'automatic-behavior.json'),JSON.stringify(automaticReport,null,2));checks.push('autonomous choices vary with random input, avoid immediate repeats, stay safe, and finish whole original GIF cycles without animating gallery movement');
  await js(`window.priorityFrames=[];window.priorityDone=null;window.priorityCount=autoLogs[0].length;await autoPets[0].select('fly',{loop:false,onComplete:value=>priorityDone=value});window.prioritySequence=autoPets[0].getState().animation.sequence;window.priorityStart=autoFrames[0].length-1`);await wait(650);assert.equal(await js('return autoLogs[0].length'),await js('return priorityCount'));assert.equal(await js(`return autoPets[0].getState().onceAction`),'fly');await until(`Boolean(priorityDone)`);assert.deepEqual(await js(`return autoFrames[0].filter(value=>value.sequence===prioritySequence).map(value=>value.frame)`),Array.from({length:35},(_,i)=>i));await until(`autoLogs[0].slice(priorityCount).some(value=>value.reason==='choice')`);checks.push('manual one-shot blocks automatic selection until all original frames finish, then random behavior resumes');
  await js(`autoPets.forEach(value=>value.destroy());autoHosts.forEach(value=>value.remove());quietPet.destroy();quietHost.remove();stillPreview.destroy();previewHost.remove()`);
  await verifyAutomaticEdge(js,until);
  await js(`await pet.playOnce('special0',{force:true});pet.setMotion(false)`);assert.ok(await js(`return pet.getState().lockedUntil-performance.now()`)>11900);checks.push('long action holds for its original 12.2 seconds rather than the upstream truncated 5.2 seconds');
  await js(`await pet.select('walk_left');pet.setMotion(true)`);const left=await js(`return pet.getState().x`);await wait(220);assert.ok(await js(`return pet.getState().x`)<left);
  await js(`await pet.select('walk_right')`);assert.equal(await js(`return pet.element.dataset.action`),'walk_right');checks.push('direction aliases share the walking GIF with correct mirror and preserved movement');
  await js(`pet.setSettings({autoBehavior:false,dragAction:'fly',edgeHide:true});await pet.select(null);pet.setPosition(350,300);pet.beginDrag({x:380,y:330});pet.moveDrag({x:460,y:420})`);
  assert.equal(await js(`return pet.getState().dragging`),true);assert.equal(await js(`return pet.getState().x`),430);assert.equal(await js(`return pet.getState().y`),390);await until(`pet.element.dataset.action==='fly'`);
  await js(`pet.endDrag()`);await until(`pet.element.dataset.action==='interact'`);checks.push('drag uses configurable original flying GIF and releases into the full touch interaction');
  await js(`await pet.select('hide')`);assert.equal(await js(`return pet.getState().hiddenEdge`),'right');assert.ok(await js(`return pet.getState().x`)>750);
  await js(`pet.wake()`);await until(`pet.element.dataset.action==='sweat'`);assert.equal(await js(`return pet.getState().hiddenEdge`),null);assert.ok(await js(`return pet.getState().x+pet.getState().width`)<800);checks.push('edge hiding leaves a clickable sliver and wake plays original sweat before returning inside the world');
  const edgePixels={};
  for(const edge of ['left','right']){
    await js(`await pet.select('sit');pet.setPosition(${edge==='left'?10:620},300);await pet.select('hide');pet.setMotion(false)`);
    edgePixels[edge]=await js(`const c=pet.element.querySelector('canvas'),data=c.getContext('2d').getImageData(0,0,c.width,c.height).data,ratio=c.width/pet.getState().width,peek=Math.ceil(Math.max(24,pet.getState().width*.216)*ratio);let visible=0;for(let y=0;y<c.height;y++)for(let x=0;x<peek;x++){const sourceX=${edge==='left'?'c.width-1-x':'x'};if(data[(y*c.width+sourceX)*4+3])visible++}return{visible,pixels:[...data],width:c.width,height:c.height,position:pet.getState().x,edge:pet.getState().hiddenEdge}`);
    assert.equal(edgePixels[edge].edge,edge);assert.ok(edgePixels[edge].visible>200);
    const rect=await js(`const r=document.querySelector('.stage').getBoundingClientRect();return{x:Math.round(r.x),y:Math.round(r.y),width:Math.round(r.width),height:Math.round(r.height)}`);fs.writeFileSync(path.join(out,'ViVi-露尾-'+edge+'.png'),(await win.webContents.capturePage(rect)).toPNG());
    await js(`pet.setMotion(true)`);
  }
  const l=edgePixels.left,r=edgePixels.right;assert.equal(l.width,r.width);let difference=0;for(let y=0;y<l.height;y++)for(let x=0;x<l.width;x++)for(let channel=0;channel<4;channel++)difference+=Math.abs(l.pixels[(y*l.width+x)*4+channel]-r.pixels[(y*r.width+r.width-1-x)*4+channel]);assert.ok(difference<l.width*l.height);checks.push('left and right tails mirror exactly, point into the viewport, and expose clickable pixels beyond transparent padding');
  await js(`pet.setSettings({scale:1.4});window.hiddenResized=pet.getState();window.notificationsBefore=positions.length;pet.resize(144,156);pet.setSettings({scale:1.4,edgeHide:true});window.notificationsAfter=positions.length;pet.setSettings({scale:1})`);assert.equal(await js('return hiddenResized.hiddenEdge'),'right');assert.ok(Math.abs(await js('return hiddenResized.x')-(800-Math.max(24,201.6*.216)))<.001);assert.equal(await js('return notificationsBefore'),await js('return notificationsAfter'));checks.push('scaling keeps the hidden tail at its edge and identical resize/settings avoid repeated position notifications');
  await js(`await pet.select('sleep');pet.beginDrag({x:pet.getState().x+20,y:pet.getState().y+20});pet.moveDrag({x:120,y:120});pet.endDrag()`);await until(`pet.element.dataset.action==='sleep'`);checks.push('a chosen loop survives dragging and resumes until explicitly changed');
  await js(`pet.setSettings({scale:1.4});pet.resize(144,156);pet.setMotion(false)`);assert.ok(Math.abs(await js(`return pet.getState().width`)-201.6)<.01);const frame=await js(`return pet.getState().frame`);await wait(180);assert.equal(await js(`return pet.getState().frame`),frame);checks.push('original scale control applies once and animation pause holds the decoded frame');
  await js(`window.previews=[];for(const descriptor of manifest.actions.filter(a=>a.asset&&!a.id.startsWith('walk_'))){const host=document.createElement('div');host.className='sample';document.querySelector('.preview').append(host);const preview=lifeosViVi.mount(host,manifest,{mode:'preview',width:96,height:104});await preview.ready;await preview.select(descriptor.id);preview.setMotion(false);const label=document.createElement('label');label.textContent=descriptor.label;host.append(label);previews.push(preview)}await pet.select('sit');pet.setSettings({scale:1});pet.setPosition(500,380)`);
  const points=await js(`return previews.map(p=>({x:p.getState().x,y:p.getState().y}))`);await wait(250);assert.deepEqual(await js(`return previews.map(p=>({x:p.getState().x,y:p.getState().y}))`),points);checks.push('gallery previews keep all original action scenes within their cards without wandering');
  fs.writeFileSync(path.join(out,'ViVi-全部动作.png'),(await win.webContents.capturePage()).toPNG());
  await js(`window.stressHost=document.createElement('div');document.querySelector('.stage').append(stressHost);window.stress=lifeosViVi.mount(stressHost,manifest,{mode:'preview',width:750,height:350});await stress.ready;await stress.select('special0');window.rapidErrors=[];await Promise.all(['fly','sleep','jump','hide','interact','special0'].map(id=>stress.select(id).catch(error=>rapidErrors.push(error.message))))`);await wait(3100);
  const cache=await js(`return lifeosViVi.cacheStats()`);assert.ok(cache.frameBytes<=cache.frameLimit);assert.ok(cache.sourceBytes<=cache.sourceLimit);assert.ok(cache.decoders<=4);assert.deepEqual(await js(`return rapidErrors`),[]);await js(`stress.destroy()`);checks.push('rapid switching and original-size long animation stay within bounded frame/source/decoder caches');
  await js(`window.fallbackHost=document.createElement('div');document.querySelector('.stage').append(fallbackHost);window.savedDecoder=window.ImageDecoder;window.ImageDecoder=undefined;window.fallback=lifeosViVi.mount(fallbackHost,manifest,{mode:'preview',width:96,height:104});await fallback.ready;window.ImageDecoder=savedDecoder;fallback.setMotion(false)`);assert.equal(await js(`return fallback.element.dataset.ready`),'true');assert.equal(await js(`return fallback.element.querySelector('img').hidden`),true);checks.push('native GIF fallback stays usable and freezes to a canvas when a browser lacks ImageDecoder');
  await js(`fallback.destroy();fallbackHost.className='pet';window.ImageDecoder=undefined;fallback=lifeosViVi.mount(fallbackHost,manifest,{mode:'companion',width:144,height:156,positionElement:fallbackHost,bounds:()=>({width:800,height:560}),position:{x:620,y:300}});await fallback.ready`);
  for(const edge of ['left','right']){await js(`await fallback.select('sit');fallback.setPosition(${edge==='left'?10:620},300);await fallback.select('hide');fallback.setMotion(false)`);assert.equal(await js(`return fallback.element.querySelector('img').style.transform.includes('scaleX(-1)')`),edge==='left');assert.ok(await js(`const c=fallback.element.querySelector('canvas'),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data,peek=Math.ceil(c.width*.216);let count=0;for(let y=0;y<c.height;y++)for(let x=0;x<peek;x++)if(d[(y*c.width+(${edge==='left'?'c.width-1-x':'x'}))*4+3])count++;return count`)>200);fs.writeFileSync(path.join(out,'ViVi-fallback-露尾-'+edge+'.png'),(await win.webContents.capturePage()).toPNG());}
  await js(`window.fallbackCompleted=null;fallback.setMotion(true);await fallback.select('fly',{loop:false,onComplete:value=>fallbackCompleted=value});window.onceGIF=await(await fetch(fallback.element.querySelector('img').src)).arrayBuffer()`);assert.equal(await js(`return new TextDecoder('latin1').decode(onceGIF).includes('NETSCAPE2.0')`),false);await until(`Boolean(fallbackCompleted)`);assert.equal(await js(`return fallbackCompleted.frames`),35);assert.equal(await js(`return fallback.getState().onceAction`),null);assert.equal(await js(`return fallback.getState().action`),'sit');checks.push('native GIF fallback removes only the loop extension and completes one unchanged animation before automatic behavior');
  await js(`window.ImageDecoder=savedDecoder`);checks.push('native GIF fallback uses the same inward-pointing tail transform when playing and paused');
  await js(`pet.destroy();previews.forEach(p=>p.destroy());fallback.destroy()`);assert.equal(await js(`return document.querySelectorAll('.viviPetStage').length`),0);checks.push('destroy removes renderers and releases decoded animations');
  const released=await js(`return lifeosViVi.cacheStats()`);assert.equal(released.mounts,0);assert.equal(released.frameBytes,0);assert.equal(released.sourceBytes,0);assert.equal(released.decoders,0);assert.equal(released.frames,0);checks.push('final unmount closes all shared bitmaps/decoders and clears cached source bytes');
  assert.deepEqual(errors,[]);checks.push('renderer emits no script errors');
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({ok:true,checks,performance:performanceReport,cache_under_pressure:cache,cache_after_destroy:released,consoleErrors:errors,visible_sample_pixels:visible,diaries_opened:0,remote_requests:0},null,2));console.log(JSON.stringify({ok:true,checks:checks.length,out}));
}
app.whenReady().then(run).then(()=>{server.close();win.destroy();app.exit(0)}).catch(error=>{fs.writeFileSync(path.join(out,'failure.txt'),error.stack);console.error(error.stack);server?.close();win?.destroy();app.exit(1)});
