'use strict';
// Source-app QA with an isolated empty workspace and shipped public sprites.
const {app,BrowserWindow,ipcMain}=require('electron');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const runtime=require('../desktop/runtime.cjs'),{createStore}=require('../desktop/workspace-store.cjs'),{normalizeSettings}=require('../desktop/pet-controller.cjs');
const ROOT=path.resolve(__dirname,'..'),out=path.join(ROOT,'docs','qa_pet_shelf','run-'+Date.now()),workspace=path.join(out,'workspace');
fs.mkdirSync(workspace,{recursive:true});fs.cpSync(path.join(ROOT,'config'),path.join(workspace,'config'),{recursive:true});
fs.cpSync(path.join(ROOT,'app','assets','pets'),path.join(workspace,'app','assets','pets'),{recursive:true});
for(const folder of ['vault','data','.lifeos'])fs.mkdirSync(path.join(workspace,folder),{recursive:true});
app.setPath('userData',path.join(out,'profile'));
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),checks=[],errors=[],metrics={};let backend,win,remoteAttempts=0,blockAtlas=true;
app.on('window-all-closed',()=>{});
async function run(){
  const store=createStore(workspace);store.operation({op:'set',key:'lifeos.welcome.v1',value:'done'});
  const port=await runtime.availablePort(),paths={dataRoot:workspace,resourceRoot:ROOT,logFile:path.join(out,'backend.log')};
  const env={...process.env,LIFEOS_PYTHON:path.join(ROOT,'desktop','python-runtime','python.exe'),PYTHON_KEYRING_BACKEND:'keyring.backends.null.Keyring'};
  for(const key of Object.keys(env))if(key.endsWith('_API_KEY')||['PYTHONHOME','PYTHONPATH','ELECTRON_RUN_AS_NODE'].includes(key))delete env[key];
  backend=runtime.startBackend(runtime.backendLaunch({...paths,isPackaged:false,env}),{...paths,port});
  const url=`http://127.0.0.1:${port}`;await runtime.waitForServer(url+'/api/health',{failure:backend.failure});
  win=new BrowserWindow({width:1320,height:940,show:false,webPreferences:{preload:path.join(ROOT,'desktop','preload.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,offscreen:true,backgroundThrottling:false}});
  ipcMain.on('lifeos:storage',(event,command)=>{try{event.returnValue={ok:true,value:store.operation(command)}}catch(error){event.returnValue={ok:false,error:error.message}}});
  ipcMain.handle('lifeos:update-status',()=>({status:'idle'}));
  let settings=normalizeSettings({});
  ipcMain.handle('lifeos:pet-settings-get',()=>({ok:true,settings}));
  ipcMain.handle('lifeos:pet-settings-set',async(_event,patch)=>{settings=normalizeSettings(patch,settings);const result={ok:true,settings};win.webContents.send('lifeos:pet-settings',result);return result});
  ipcMain.handle('lifeos:pet-action',()=>({ok:true}));ipcMain.handle('lifeos:pet-refresh',()=>({ok:true,settings}));
  win.webContents.on('console-message',details=>{if(details.level==='error'&&!/net::ERR|Failed to load resource/.test(details.message))errors.push(details.message)});
  win.webContents.session.webRequest.onBeforeRequest({urls:['https://*/*','http://*/*']},(details,callback)=>{
    if(details.url.startsWith(url))return callback({});
    if(/^https:\/\/raw\.githubusercontent\.com\/legeling\/awesome-codex-pet\/main\/pets\/[^/]+\/spritesheet\.webp$/.test(details.url)){
      remoteAttempts++;return blockAtlas?callback({cancel:true}):callback({redirectURL:url+'/assets/pets/drill-cat--qimi/spritesheet.webp'});
    }
    callback({cancel:true});
  });
  win.webContents.session.webRequest.onHeadersReceived({urls:[url+'/assets/pets/*']},(details,callback)=>callback({responseHeaders:{...details.responseHeaders,'Access-Control-Allow-Origin':['*']}}));
  await win.loadURL(url);
  const js=code=>win.webContents.executeJavaScript(`(async()=>{${code}})()`);
  const until=async condition=>{for(let i=0;i<120;i++){if(await js('return '+condition))return;await wait(100)}throw Error('Wait failed: '+condition)};
  const shot=async name=>{await wait(220);fs.writeFileSync(path.join(out,name+'.png'),(await win.webContents.capturePage()).toPNG())};
  const openKeyboardMenu=async selector=>{
    await js(`const el=document.querySelector(${JSON.stringify(selector)});el.focus({preventScroll:true});el.dispatchEvent(new KeyboardEvent('keydown',{key:'F10',shiftKey:true,bubbles:true}))`);
    await until(`!!document.querySelector('#petActionMenu:not([hidden])')`);
  };
  const clickAction=async action=>{
    assert.equal(await js(`return document.querySelector('#petActionMenu [data-pet-action="${action}"]').getAttribute('role')`),'menuitem');
    await js(`document.querySelector('#petActionMenu [data-pet-action="${action}"]').click()`);
  };
  const startFrameCapture=async(selectors,action)=>js(`
    window.__atlasFrameCapture?.stop();const targets=${JSON.stringify(selectors)},chosen=${JSON.stringify(action)},started=performance.now(),records={};
    const observers=[];for(const selector of targets){const el=document.querySelector(selector);records[selector]=[];
      const sample=()=>{if(el.dataset.petAction!==chosen)return;const css=el.style.backgroundPosition,column=selector==='#lifePetFloatSprite'?-parseFloat(css)/el.clientWidth:Math.round(parseFloat(css)*7/100),list=records[selector];
        if(!list.length||list.at(-1).column!==column)list.push({column,ms:performance.now()-started,css});};
      const observer=new MutationObserver(sample);observer.observe(el,{attributes:true,attributeFilter:['style','data-pet-action']});observers.push(observer);sample();}
    window.__atlasFrameCapture={records,stop(){observers.forEach(observer=>observer.disconnect());return records;}};
  `);
  const frameCapture=async()=>js(`return window.__atlasFrameCapture.stop()`);
  const checkFrames=(records,selector,expected,interval)=>{
    assert.deepEqual(records[selector].map(item=>Math.round(item.column)||0),expected,selector+' shows every occupied frame once');
    const gaps=records[selector].slice(1).map((item,index)=>item.ms-records[selector][index].ms);
    assert.ok(gaps.every(gap=>gap>=interval*.65&&gap<=interval*2),selector+' keeps its existing animation cadence');
    return {frames:records[selector].map(item=>Math.round(item.column)||0),gaps_ms:gaps.map(ms=>Math.round(ms))};
  };
  await until(`!!window.lifeosPetActions&&!!window.lifeosSidebar`);await wait(1400);
  await js(`window.dispatchEvent(new Event('lifeos:open-pet'))`);await until(`!!document.querySelector('#petPageCatalog .petPageCard')`);
  assert.equal(await js(`return document.querySelector('.petPage').dataset.columns`),'2');
  assert.equal(await js(`return getComputedStyle(document.querySelector('#petPageCatalog')).gridTemplateColumns.split(' ').length`),2);
  assert.equal(await js(`return !!document.querySelector('.petPageActions,#petPageExamples')`),false);
  assert.equal(remoteAttempts,0);checks.push('default two-column shelf removes bulk action controls and loads no remote atlas');
  await js(`document.querySelector('.petPageLibrary').scrollIntoView({block:'start'})`);await shot('灵犀-两列宠物库');
  for(const columns of [1,4,2]){
    await js(`document.querySelector('[data-pet-columns="${columns}"]').click()`);
    assert.equal(await js(`return getComputedStyle(document.querySelector('#petPageCatalog')).gridTemplateColumns.split(' ').length`),columns);
    assert.equal(await js(`return localStorage.getItem('lifeos.pet.columns')`),String(columns));
    assert.equal(await js(`return document.querySelector('[data-pet-columns="${columns}"]').textContent.trim()`),'');
    if(columns===4)await shot('灵犀-四列宠物库');
  }
  checks.push('icon-only one/two/four-column controls change actual layout and persist');
  await js(`document.querySelector('[data-pet-columns="4"]').click()`);await win.webContents.reload();
  await until(`!!window.lifeosPetActions&&!!window.lifeosSidebar`);await wait(1400);await js(`window.dispatchEvent(new Event('lifeos:open-pet'))`);await until(`!!document.querySelector('#petPageCatalog .petPageCard')`);
  assert.equal(await js(`return document.querySelector('.petPage').dataset.columns`),'4');
  win.setSize(640,800);await wait(400);assert.equal(await js(`return getComputedStyle(document.querySelector('#petPageCatalog')).gridTemplateColumns.split(' ').length`),2);
  win.setSize(430,780);await wait(400);assert.equal(await js(`return getComputedStyle(document.querySelector('#petPageCatalog')).gridTemplateColumns.split(' ').length`),1);
  assert.equal(await js(`return document.documentElement.scrollWidth<=document.documentElement.clientWidth`),true);
  checks.push('column preference survives reload and narrow windows collapse to two then one without horizontal overflow');
  win.setSize(1320,940);await wait(300);await js(`document.querySelector('[data-pet-columns="2"]').click()`);
  const defaultCatalogCount=await js(`return document.querySelectorAll('#petPageCatalog .petPageCard').length`);
  await js(`document.querySelector('#petPageSearch').scrollIntoView({block:'center'});const input=document.querySelector('#petPageSearch'),category=document.querySelector('#petPageCategory');input.value='no-such-pet-2026';input.dispatchEvent(new Event('input',{bubbles:true}));category.value=category.options[1].value;category.dispatchEvent(new Event('change',{bubbles:true}))`);
  assert.equal(await js(`return document.querySelectorAll('#petPageCatalog .petPageCard').length`),0);
  assert.equal(await js(`return document.querySelector('#petPageSearchClear').hidden`),false);await shot('宠物库-清除前');
  await js(`document.querySelector('#petPageSearchClear').click();document.querySelector('#petPageSearch').scrollIntoView({block:'center'})`);
  assert.equal(await js(`return document.querySelector('#petPageSearch').value`),'');assert.equal(await js(`return document.querySelector('#petPageCategory').value`),'all');
  assert.equal(await js(`return document.querySelectorAll('#petPageCatalog .petPageCard').length`),defaultCatalogCount);await shot('宠物库-清除后');
  await js(`const input=document.querySelector('#petPageSearch');input.value='vivi';input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))`);
  assert.equal(await js(`return document.querySelector('#petPageSearch').value`),'');assert.equal(await js(`return document.querySelectorAll('#petPageCatalog .petPageCard').length`),defaultCatalogCount);
  checks.push('pet library clear icon and Escape restore the default list and filters, with the actual controls captured before and after clearing');
  const atlas=await js(`const data=await (await fetch('/api/pets/catalog',{cache:'no-store'})).json();return data.installed.find(item=>item.folder==='desk-otter'&&item.renderer!=='vivi-gif')||data.installed.find(item=>item.renderer!=='vivi-gif')`);assert.ok(atlas);
  await js(`document.querySelector('#petPageInstalled [data-pet-activate="${atlas.slug}"]').click()`);
  await until(`document.querySelector('#petPageSprite')?.dataset.petTarget==='${atlas.slug}'&&document.querySelector('#lifePetFloatSprite')?.style.backgroundImage.includes('${atlas.folder}')`);
  assert.equal(await js(`return (await (await fetch('/api/pets/catalog',{cache:'no-store'})).json()).active_slug`),atlas.slug);
  const prepared=await js(`return lifeosPetSprites.prepare(${JSON.stringify(atlas)})`);
  const secondary=await js(`const data=await (await fetch('/api/pets/catalog',{cache:'no-store'})).json();return data.installed.find(item=>item.slug!=='${atlas.slug}'&&item.renderer!=='vivi-gif')`);assert.ok(secondary);
  const secondaryPrepared=await js(`return lifeosPetSprites.prepare(${JSON.stringify(secondary)})`);
  await until(`document.querySelector('#petPageSprite').dataset.petAction==='idle'&&document.querySelector('#lifePetFloatSprite').dataset.petAction==='idle'&&lifeosPetActions.selected('${atlas.slug}')===null`);
  checks.push('real installed Desk Otter activation through the shelf reaches the catalog API, hero and in-app atlas companion');
  win.webContents.debugger.attach('1.3');const cdp=win.webContents.debugger;
  await js(`document.querySelector('.petPageHeroPet').scrollIntoView({block:'center'})`);await wait(200);
  const automaticState=await js(`return document.querySelector('#petPageSprite').dataset.petAction`);
  const hero=await js(`const r=document.querySelector('#petPageSprite').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}`);
  assert.ok(hero.x>0&&hero.y>0&&hero.x<1320&&hero.y<940,'native right-click target is visible');
  await cdp.sendCommand('Input.dispatchMouseEvent',{type:'mousePressed',...hero,button:'right',clickCount:1});await cdp.sendCommand('Input.dispatchMouseEvent',{type:'mouseReleased',...hero,button:'right',clickCount:1});
  await until(`!!document.querySelector('#petActionMenu:not([hidden])')`);await shot('灵犀-右键动作');
  await startFrameCapture(['#petPageSprite','#lifePetFloatSprite'],'waving');await clickAction('waving');
  await until(`document.querySelector('#petPageSprite').dataset.petAction==='waving'&&document.querySelector('#lifePetFloatSprite').dataset.petAction==='waving'`);
  const firstCommand=await js(`return lifeosPetActions.command('${atlas.slug}').requestId`);
  await until(`document.querySelector('#petPageSprite').dataset.petAction!=='waving'&&document.querySelector('#lifePetFloatSprite').dataset.petAction!=='waving'&&lifeosPetActions.selected('${atlas.slug}')===null`);
  const captured=await frameCapture();metrics.hero_once=checkFrames(captured,'#petPageSprite',prepared.frame_map[3],155);metrics.float_once=checkFrames(captured,'#lifePetFloatSprite',prepared.frame_map[3],140);
  assert.equal(await js(`return document.querySelector('#petPageSprite').dataset.petAction`),automaticState);
  assert.equal(await js(`return document.querySelector('#lifePetFloatSprite').dataset.petAction`),'idle');
  checks.push('real right-click action completes every populated atlas frame once at the original cadence, then returns to automatic animation');
  await openKeyboardMenu('#petPageSprite');await startFrameCapture(['#petPageSprite'],'waving');await clickAction('waving');
  assert.notEqual(await js(`return lifeosPetActions.command('${atlas.slug}').requestId`),firstCommand);
  await until(`document.querySelector('#petPageSprite').dataset.petAction!=='waving'&&lifeosPetActions.selected('${atlas.slug}')===null`);
  metrics.replay=checkFrames(await frameCapture(),'#petPageSprite',prepared.frame_map[3],155);
  checks.push('the same menu action creates a new command and replays the complete atlas cycle');
  const secondarySelector=`[data-pet-mini="${secondary.slug}"]`;
  await openKeyboardMenu(secondarySelector);await startFrameCapture([secondarySelector],'jumping');await clickAction('jumping');
  await until(`document.querySelector('${secondarySelector}').dataset.petAction==='jumping'`);
  assert.equal(await js(`return document.querySelector('#petPageSprite').dataset.petAction`),automaticState);
  await shot('灵犀-独立单次动作');
  await until(`document.querySelector('${secondarySelector}').dataset.petAction==='idle'&&lifeosPetActions.selected('${secondary.slug}')===null`);
  metrics.secondary_once=checkFrames(await frameCapture(),secondarySelector,secondaryPrepared.frame_map[4],155);
  checks.push('keyboard menu plays another installed atlas once without changing the active pet, and the mini returns to idle');
  await js(`openFeature('Time Capsule')`);await until(`STATE.feature==='Time Capsule'&&!!document.querySelector('.bottlePage')`);
  await js(`window.dispatchEvent(new Event('lifeos:open-pet'))`);await until(`!!document.querySelector('#petPageSprite')`);
  assert.notEqual(await js(`return document.querySelector('#petPageSprite').dataset.petAction`),'waving');
  assert.equal(await js(`return document.querySelector('${secondarySelector}').dataset.petAction`),'idle');
  assert.equal(await js(`return lifeosPetActions.selected('${atlas.slug}')`),null);assert.equal(await js(`return lifeosPetActions.selected('${secondary.slug}')`),null);
  await wait(600);assert.notEqual(await js(`return document.querySelector('#petPageSprite').dataset.petAction`),'waving');
  checks.push('completed commands stay finished when leaving and returning to the shelf and never revive old actions');
  await js(`document.querySelector('#petPageMotion').click()`);const still=await js(`return document.querySelector('#lifePetFloatSprite').style.backgroundPosition`);await wait(500);assert.equal(await js(`return document.querySelector('#lifePetFloatSprite').style.backgroundPosition`),still);await js(`document.querySelector('#petPageMotion').click()`);checks.push('motion switch pauses both shelf and floating companion');
  const slug=await js(`const catalog=await (await fetch('/api/pets/catalog')).json(),v2=new Set(catalog.catalog.filter(item=>item.spriteVersionNumber===2).map(item=>item.slug));return [...document.querySelectorAll('#petPageCatalog figure')].find(el=>v2.has(el.dataset.petTarget)&&!document.querySelector('[data-pet-mini="'+el.dataset.petTarget+'"]')).dataset.petTarget`);
  await js(`document.querySelector('#petPageCatalog figure[data-pet-target="${slug}"]').scrollIntoView({block:'center'})`);await wait(250);
  await js(`const el=document.querySelector('#petPageCatalog figure[data-pet-target="${slug}"]');el.focus({preventScroll:true});el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))`);await until(`!!document.querySelector('#petActionMenu:not([hidden])')`);
  assert.equal(remoteAttempts,0);await clickAction('waving');await until(`!!document.querySelector('#petActionMenu [role="status"]:not([hidden])')`);
  assert.equal(await js(`return lifeosPetActions.selected('${slug}')`),null);assert.equal(await js(`return !!document.querySelector('#petPageCatalog figure[data-pet-target="${slug}"] img')`),true);
  checks.push('uninstalled pet action downloads only after explicit choice; failed load keeps original preview and is retryable');
  blockAtlas=false;await clickAction('waving');await until(`!!document.querySelector('[data-pet-catalog-mini="${slug}"]')`);
  assert.equal(await js(`return document.querySelector('[data-pet-catalog-mini="${slug}"]').dataset.petAction`),'waving');assert.equal(await js(`return !!document.querySelector('[data-pet-mini="${slug}"]')`),false);
  await until(`document.querySelector('[data-pet-catalog-mini="${slug}"]').dataset.petAction==='idle'&&lifeosPetActions.selected('${slug}')===null`);
  assert.equal(await js(`return (await (await fetch('/api/pets/catalog',{cache:'no-store'})).json()).active_slug`),atlas.slug);
  checks.push('retry reads a v2 atlas, plays an uninstalled preview once and returns to idle without installing or activating it');
  win.setSize(430,480);await wait(300);
  await js(`document.querySelector('#lifePetFloatSprite').dispatchEvent(new KeyboardEvent('keydown',{key:'F10',shiftKey:true,bubbles:true}))`);await until(`!!document.querySelector('#petActionMenu:not([hidden])')`);
  await js(`document.querySelector('#petActionMenu').dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}))`);await wait(200);
  assert.equal(await js(`return document.querySelector('#petActionMenu').hidden`),false);assert.equal(await js(`return document.activeElement.dataset.petAction`),'auto');
  assert.equal(await js(`const r=document.querySelector('#petActionMenu').getBoundingClientRect();return r.top>=10&&r.bottom<=document.documentElement.clientHeight-9`),true);
  await js(`document.querySelector('#petActionMenu').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))`);
  assert.equal(await js(`return document.activeElement.id`),'lifePetFloatSprite');checks.push('short viewport menu stays open while keyboard navigation scrolls internally and Escape restores focus');
  const touch=await js(`const r=document.querySelector('#lifePetFloatSprite').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}`);
  await cdp.sendCommand('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...touch,id:7,radiusX:1,radiusY:1,force:1}]});await wait(580);
  await cdp.sendCommand('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await until(`!!document.querySelector('#petActionMenu:not([hidden])')`);await clickAction('waving');await until(`document.querySelector('#petActionMenu').hidden`);
  await until(`document.querySelector('#lifePetFloatSprite').dataset.petAction==='waving'`);await until(`document.querySelector('#lifePetFloatSprite').dataset.petAction==='idle'&&lifeosPetActions.selected('${atlas.slug}')===null`);
  checks.push('touch long press opens the same action menu, plays the chosen action once, and restores automatic idle');
  win.setSize(1320,940);await wait(200);
  await js(`window.__originalFetch=window.fetch;window.__chatPayloads=[];window.fetch=async(input,options)=>{if(input==='/api/pets/chat'){__chatPayloads.push(JSON.parse(options.body));return new Response(JSON.stringify({ok:true,reply:'打开界面微调，选择编辑侧栏，即可拖动排序或收进阁楼',mode:'local_guide',knowledge:{sources:[{id:'sidebar',title:'侧栏',entry:'界面微调 → 编辑侧栏',action:'appearance',content:'PRIVATE_GUIDE_NOT_IN_CHAT_PAYLOAD'}]}}),{status:200,headers:{'Content-Type':'application/json'}})}return __originalFetch(input,options)};window.dispatchEvent(new Event('lifeos:open-pet-chat'));document.querySelector('#petChatInput').value='怎么调整侧边栏';document.querySelector('#petChatForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))`);
  await until(`!!document.querySelector('.petChatSources button')`);assert.equal(await js(`return document.querySelector('.petChatSources small').textContent`),'本地指南');await shot('灵犀-本地使用指南');
  await js(`document.querySelector('#petChatInput').value='再告诉我白噪音在哪';document.querySelector('#petChatForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))`);await until(`__chatPayloads.length===2`);
  assert.equal(await js(`return JSON.stringify(__chatPayloads).includes('PRIVATE_GUIDE_NOT_IN_CHAT_PAYLOAD')`),false);
  await js(`document.querySelector('#allRail').click();document.querySelector('.petChatSources button').click()`);assert.equal(await js(`return document.querySelector('#tweaksPanel').classList.contains('open')`),true);
  checks.push('local guide shows compact actionable source links and does not resend knowledge source content in future chat payloads');
  win.webContents.debugger.detach();assert.deepEqual(errors,[]);checks.push('source Electron has no renderer script errors');
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({ok:true,checks,metrics,atlas_slug:atlas.slug,isolated_workspace:true,remote_ai_calls:0,remote_atlas_fixture_attempts:remoteAttempts},null,2));console.log(JSON.stringify({ok:true,checks:checks.length,metrics,out}));
}
app.whenReady().then(run).then(()=>{backend?.child?.kill();win?.destroy();app.exit(0)}).catch(async error=>{fs.writeFileSync(path.join(out,'failure.txt'),error.stack);if(win&&!win.isDestroyed()){const diagnostic=await win.webContents.executeJavaScript(`({feature:STATE.feature,active:document.querySelector('#petPageSprite')?.dataset.petTarget,hero:document.querySelector('#petPageSprite')?.getBoundingClientRect().toJSON(),menu:document.querySelector('#petActionMenu')?.textContent,menuHidden:document.querySelector('#petActionMenu')?.hidden,frameCapture:window.__atlasFrameCapture?.stop(),errors:[]})`).catch(()=>null);fs.writeFileSync(path.join(out,'failure-state.json'),JSON.stringify({checks,metrics,remoteAttempts,errors,diagnostic},null,2));fs.writeFileSync(path.join(out,'failure.png'),(await win.webContents.capturePage()).toPNG());}console.error(error.stack);backend?.child?.kill();win?.destroy();app.exit(1)});
