'use strict';
// Source-app QA with an isolated empty workspace and shipped public sprites.
const {app,BrowserWindow,ipcMain}=require('electron');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const runtime=require('../desktop/runtime.cjs'),{createStore}=require('../desktop/workspace-store.cjs');
const ROOT=path.resolve(__dirname,'..'),out=path.join(ROOT,'docs','qa_pet_shelf','run-'+Date.now()),workspace=path.join(out,'workspace');
fs.mkdirSync(workspace,{recursive:true});fs.cpSync(path.join(ROOT,'config'),path.join(workspace,'config'),{recursive:true});
fs.cpSync(path.join(ROOT,'app','assets','pets'),path.join(workspace,'app','assets','pets'),{recursive:true});
for(const folder of ['vault','data','.lifeos'])fs.mkdirSync(path.join(workspace,folder),{recursive:true});
app.setPath('userData',path.join(out,'profile'));
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),checks=[],errors=[];let backend,win,remoteAttempts=0,blockAtlas=true;
app.on('window-all-closed',()=>{});
async function run(){
  const store=createStore(workspace);store.operation({op:'set',key:'lifeos.welcome.v1',value:'done'});
  const port=await runtime.availablePort(),paths={dataRoot:workspace,resourceRoot:ROOT,logFile:path.join(out,'backend.log')};
  const env={...process.env,LIFEOS_PYTHON:path.join(ROOT,'desktop','python-runtime','python.exe'),PYTHON_KEYRING_BACKEND:'keyring.backends.null.Keyring'};
  for(const key of Object.keys(env))if(key.endsWith('_API_KEY')||['PYTHONHOME','PYTHONPATH','ELECTRON_RUN_AS_NODE'].includes(key))delete env[key];
  backend=runtime.startBackend(runtime.backendLaunch({...paths,isPackaged:false,env}),{...paths,port});
  const url=`http://127.0.0.1:${port}`;await runtime.waitForServer(url+'/api/health',{failure:backend.failure});
  win=new BrowserWindow({width:1320,height:940,show:false,webPreferences:{preload:path.join(ROOT,'desktop','preload.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,offscreen:true,backgroundThrottling:false}});
  ipcMain.on('lifeos:storage',(event,command)=>{try{event.returnValue={ok:true,value:store.operation(command)}}catch(error){event.returnValue={ok:false,error:error.message}}});
  ipcMain.handle('lifeos:update-status',()=>({status:'idle'}));
  win.webContents.on('console-message',details=>{if(details.level==='error'&&!/net::ERR|Failed to load resource/.test(details.message))errors.push(details.message)});
  win.webContents.session.webRequest.onBeforeRequest({urls:['https://*/*','http://*/*']},(details,callback)=>{
    if(details.url.startsWith(url))return callback({});
    if(/^https:\/\/raw\.githubusercontent\.com\/legeling\/awesome-codex-pet\/main\/pets\/[^/]+\/spritesheet\.webp$/.test(details.url)){
      remoteAttempts++;return blockAtlas?callback({cancel:true}):callback({redirectURL:url+'/assets/pets/drill-cat--qimi/spritesheet.webp'});
    }
    callback({cancel:true});
  });
  win.webContents.session.webRequest.onHeadersReceived({urls:[url+'/assets/pets/*']},(details,callback)=>callback({responseHeaders:{...details.responseHeaders,'Access-Control-Allow-Origin':['*']}}));
  await win.loadURL(url);
  const js=code=>win.webContents.executeJavaScript(`(async()=>{${code}})()`);
  const until=async condition=>{for(let i=0;i<120;i++){if(await js('return '+condition))return;await wait(100)}throw Error('Wait failed: '+condition)};
  const shot=async name=>{await wait(220);fs.writeFileSync(path.join(out,name+'.png'),(await win.webContents.capturePage()).toPNG())};
  await until(`!!window.lifeosPetActions&&!!window.lifeosSidebar`);await wait(1400);
  await js(`window.dispatchEvent(new Event('lifeos:open-pet'))`);await until(`!!document.querySelector('#petPageCatalog .petPageCard')`);
  assert.equal(await js(`return document.querySelector('.petPage').dataset.columns`),'2');
  assert.equal(await js(`return getComputedStyle(document.querySelector('#petPageCatalog')).gridTemplateColumns.split(' ').length`),2);
  assert.equal(await js(`return !!document.querySelector('.petPageActions,#petPageExamples')`),false);
  assert.equal(remoteAttempts,0);checks.push('default two-column shelf removes bulk action controls and loads no remote atlas');
  await js(`document.querySelector('.petPageLibrary').scrollIntoView({block:'start'})`);await shot('灵犀-两列宠物库');
  for(const columns of [1,4,2]){
    await js(`document.querySelector('[data-pet-columns="${columns}"]').click()`);
    assert.equal(await js(`return getComputedStyle(document.querySelector('#petPageCatalog')).gridTemplateColumns.split(' ').length`),columns);
    assert.equal(await js(`return localStorage.getItem('lifeos.pet.columns')`),String(columns));
    assert.equal(await js(`return document.querySelector('[data-pet-columns="${columns}"]').textContent.trim()`),'');
    if(columns===4)await shot('灵犀-四列宠物库');
  }
  checks.push('icon-only one/two/four-column controls change actual layout and persist');
  await js(`document.querySelector('[data-pet-columns="4"]').click()`);await win.webContents.reload();
  await until(`!!window.lifeosPetActions&&!!window.lifeosSidebar`);await wait(1400);await js(`window.dispatchEvent(new Event('lifeos:open-pet'))`);await until(`!!document.querySelector('#petPageCatalog .petPageCard')`);
  assert.equal(await js(`return document.querySelector('.petPage').dataset.columns`),'4');
  win.setSize(640,800);await wait(400);assert.equal(await js(`return getComputedStyle(document.querySelector('#petPageCatalog')).gridTemplateColumns.split(' ').length`),2);
  win.setSize(430,780);await wait(400);assert.equal(await js(`return getComputedStyle(document.querySelector('#petPageCatalog')).gridTemplateColumns.split(' ').length`),1);
  assert.equal(await js(`return document.documentElement.scrollWidth<=document.documentElement.clientWidth`),true);
  checks.push('column preference survives reload and narrow windows collapse to two then one without horizontal overflow');
  win.setSize(1320,940);await wait(300);await js(`document.querySelector('[data-pet-columns="2"]').click()`);
  const slugs=await js(`return [...document.querySelectorAll('[data-pet-mini]')].map(el=>el.dataset.petMini)`);assert.ok(slugs.length>=3);
  win.webContents.debugger.attach('1.3');const cdp=win.webContents.debugger;
  await js(`document.querySelector('#petPageInstalled').scrollIntoView({block:'center'})`);await wait(200);
  const hero=await js(`const r=document.querySelector('#petPageSprite').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}`);
  await cdp.sendCommand('Input.dispatchMouseEvent',{type:'mousePressed',...hero,button:'right',clickCount:1});await cdp.sendCommand('Input.dispatchMouseEvent',{type:'mouseReleased',...hero,button:'right',clickCount:1});
  await until(`!!document.querySelector('#petActionMenu:not([hidden])')`);await shot('灵犀-右键动作');
  await js(`document.querySelector('#petActionMenu [data-pet-loop="waving"]').click()`);await until(`document.querySelector('#petPageSprite').dataset.petAction==='waving'`);
  assert.equal(await js(`return document.querySelector('#lifePetFloatSprite').dataset.petAction`),'waving');await wait(1800);
  assert.equal(await js(`return document.querySelector('#lifePetFloatSprite').dataset.petAction`),'waving');
  checks.push('real right-click menu applies a loop shared with the active in-app companion beyond transient animation duration');
  await js(`const el=document.querySelector('[data-pet-mini="${slugs[1]}"]');el.focus();el.dispatchEvent(new KeyboardEvent('keydown',{key:'F10',shiftKey:true,bubbles:true}))`);
  await until(`!!document.querySelector('#petActionMenu:not([hidden])')`);await js(`document.querySelector('#petActionMenu [data-pet-loop="jumping"]').click()`);
  assert.equal(await js(`return document.querySelector('[data-pet-mini="${slugs[1]}"]').dataset.petAction`),'jumping');
  assert.equal(await js(`return document.querySelector('#petPageSprite').dataset.petAction`),'waving');
  const before=await js(`return document.querySelector('[data-pet-mini="${slugs[1]}"]').style.backgroundPosition`);await wait(190);
  assert.notEqual(await js(`return document.querySelector('[data-pet-mini="${slugs[1]}"]').style.backgroundPosition`),before);
  await shot('灵犀-独立循环');checks.push('keyboard context menu starts a second pet action without changing the active pet and installed mini animation advances');
  await js(`await openFeature('Time Capsule');window.dispatchEvent(new Event('lifeos:open-pet'))`);await until(`document.querySelector('#petPageSprite')?.dataset.petAction==='waving'`);
  assert.equal(await js(`return document.querySelector('[data-pet-mini="${slugs[1]}"]').dataset.petAction`),'jumping');checks.push('each pet action survives leaving and returning to the shelf in this session');
  await js(`document.querySelector('#petPageMotion').click()`);const still=await js(`return document.querySelector('#lifePetFloatSprite').style.backgroundPosition`);await wait(500);assert.equal(await js(`return document.querySelector('#lifePetFloatSprite').style.backgroundPosition`),still);await js(`document.querySelector('#petPageMotion').click()`);checks.push('motion switch pauses both shelf and floating companion');
  const slug=await js(`const catalog=await (await fetch('/api/pets/catalog')).json(),v2=new Set(catalog.catalog.filter(item=>item.spriteVersionNumber===2).map(item=>item.slug));return [...document.querySelectorAll('#petPageCatalog figure')].find(el=>v2.has(el.dataset.petTarget)&&!document.querySelector('[data-pet-mini="'+el.dataset.petTarget+'"]')).dataset.petTarget`);
  await js(`document.querySelector('#petPageCatalog figure[data-pet-target="${slug}"]').scrollIntoView({block:'center'})`);await wait(250);
  await js(`const el=document.querySelector('#petPageCatalog figure[data-pet-target="${slug}"]');el.focus({preventScroll:true});el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))`);await until(`!!document.querySelector('#petActionMenu:not([hidden])')`);
  assert.equal(remoteAttempts,0);await js(`document.querySelector('#petActionMenu [data-pet-loop="waving"]').click()`);await until(`!!document.querySelector('#petActionMenu [role="status"]:not([hidden])')`);
  assert.equal(await js(`return lifeosPetActions.selected('${slug}')`),null);assert.equal(await js(`return !!document.querySelector('#petPageCatalog figure[data-pet-target="${slug}"] img')`),true);
  checks.push('uninstalled pet action downloads only after explicit choice; failed load keeps original preview and is retryable');
  blockAtlas=false;await js(`document.querySelector('#petActionMenu [data-pet-loop="waving"]').click()`);await until(`!!document.querySelector('[data-pet-catalog-mini="${slug}"]')`);
  assert.equal(await js(`return document.querySelector('[data-pet-catalog-mini="${slug}"]').dataset.petAction`),'waving');assert.equal(await js(`return !!document.querySelector('[data-pet-mini="${slug}"]')`),false);
  checks.push('retry reads populated v2 atlas frames and loops an uninstalled pet without installing or activating it');
  win.setSize(430,480);await wait(300);
  await js(`document.querySelector('#lifePetFloatSprite').dispatchEvent(new KeyboardEvent('keydown',{key:'F10',shiftKey:true,bubbles:true}))`);await until(`!!document.querySelector('#petActionMenu:not([hidden])')`);
  await js(`document.querySelector('#petActionMenu').dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}))`);await wait(200);
  assert.equal(await js(`return document.querySelector('#petActionMenu').hidden`),false);assert.equal(await js(`return document.activeElement.dataset.petLoop`),'auto');
  assert.equal(await js(`const r=document.querySelector('#petActionMenu').getBoundingClientRect();return r.top>=10&&r.bottom<=document.documentElement.clientHeight-9`),true);
  await js(`document.querySelector('#petActionMenu').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))`);
  assert.equal(await js(`return document.activeElement.id`),'lifePetFloatSprite');checks.push('short viewport menu stays open while keyboard navigation scrolls internally and Escape restores focus');
  const touch=await js(`const r=document.querySelector('#lifePetFloatSprite').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}`);
  await cdp.sendCommand('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...touch,id:7,radiusX:1,radiusY:1,force:1}]});await wait(580);
  await cdp.sendCommand('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await until(`!!document.querySelector('#petActionMenu:not([hidden])')`);await js(`document.querySelector('#petActionMenu [data-pet-loop="waving"]').click()`);await until(`document.querySelector('#petActionMenu').hidden`);
  checks.push('touch long press opens the same action menu without dragging or clearing the chosen loop');
  win.setSize(1320,940);await wait(200);
  await js(`window.__originalFetch=window.fetch;window.__chatPayloads=[];window.fetch=async(input,options)=>{if(input==='/api/pets/chat'){__chatPayloads.push(JSON.parse(options.body));return new Response(JSON.stringify({ok:true,reply:'打开界面微调，选择编辑侧栏，即可拖动排序或收进阁楼',mode:'local_guide',knowledge:{sources:[{id:'sidebar',title:'侧栏',entry:'界面微调 → 编辑侧栏',action:'appearance',content:'PRIVATE_GUIDE_NOT_IN_CHAT_PAYLOAD'}]}}),{status:200,headers:{'Content-Type':'application/json'}})}return __originalFetch(input,options)};window.dispatchEvent(new Event('lifeos:open-pet-chat'));document.querySelector('#petChatInput').value='怎么调整侧边栏';document.querySelector('#petChatForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))`);
  await until(`!!document.querySelector('.petChatSources button')`);assert.equal(await js(`return document.querySelector('.petChatSources small').textContent`),'本地指南');await shot('灵犀-本地使用指南');
  await js(`document.querySelector('#petChatInput').value='再告诉我白噪音在哪';document.querySelector('#petChatForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))`);await until(`__chatPayloads.length===2`);
  assert.equal(await js(`return JSON.stringify(__chatPayloads).includes('PRIVATE_GUIDE_NOT_IN_CHAT_PAYLOAD')`),false);
  await js(`document.querySelector('#allRail').click();document.querySelector('.petChatSources button').click()`);assert.equal(await js(`return document.querySelector('#tweaksPanel').classList.contains('open')`),true);
  checks.push('local guide shows compact actionable source links and does not resend knowledge source content in future chat payloads');
  win.webContents.debugger.detach();assert.deepEqual(errors,[]);checks.push('source Electron has no renderer script errors');
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({ok:true,checks,isolated_workspace:true,remote_ai_calls:0,remote_atlas_fixture_attempts:remoteAttempts},null,2));console.log(JSON.stringify({ok:true,checks:checks.length,out}));
}
app.whenReady().then(run).then(()=>{backend?.child?.kill();win?.destroy();app.exit(0)}).catch(async error=>{fs.writeFileSync(path.join(out,'failure.txt'),error.stack);if(win&&!win.isDestroyed()){const diagnostic=await win.webContents.executeJavaScript(`({feature:STATE.feature,menu:document.querySelector('#petActionMenu')?.textContent,menuHidden:document.querySelector('#petActionMenu')?.hidden,errors:[]})`).catch(()=>null);fs.writeFileSync(path.join(out,'failure-state.json'),JSON.stringify({remoteAttempts,errors,diagnostic},null,2));}console.error(error.stack);backend?.child?.kill();win?.destroy();app.exit(1)});
